services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: voice_chatbot_backend
    ports:
      - "3100:3100"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./api:/home/backend/api
    restart: unless-stopped
