"""Chat request and response schemas."""

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Request schema for /chat endpoint."""

    user_message: str = Field(
        ...,
        description="The message from the user to be processed by the agent.",
        min_length=1,
    )
    thread_id: str | None = Field(
        default=None,
        description="Optional conversation thread ID to maintain context across turns.",
    )


class ChatResponse(BaseModel):
    """Response schema for /chat endpoint."""

    response: str = Field(
        ...,
        description="The textual response generated by the agent.",
    )
    thread_id: str = Field(
        ...,
        description="The conversation thread ID for this session.",
    )
